import { Injectable, InternalServerErrorException, Logger } from '@nestjs/common';
import * as QRCode from 'qrcode';
import PQueue from 'p-queue';
import { BrowserService } from './browser.service';
import { GenerateReceiptDto } from './dto/receipt.dto';

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private queue = new PQueue({ concurrency: 5 }); // Limit concurrent renders

  constructor(private readonly browserService: BrowserService) {}

  async generateReceiptPdf(data: GenerateReceiptDto): Promise<Buffer> {
    return this.queue.add(() => this.executePdfGeneration(data));
  }

  private async executePdfGeneration(data: GenerateReceiptDto, retries = 2): Promise<Buffer> {
    const context = await this.browserService.createNewContext();
    const page = await context.newPage();

    try {
      const qrCodeDataUrl = await QRCode.toDataURL(data.verifyUrl);
      const htmlContent = this.getHtmlTemplate(data, qrCodeDataUrl);

      await page.setContent(htmlContent, { 
        waitUntil: 'networkidle0',
        timeout: 30000 
      });

      // Repeating Header Template
      const headerTemplate = `
        <div style="font-size: 10px; width: 100%; border-bottom: 1px solid #eee; padding-bottom: 5px; margin: 0 40px; display: flex; justify-content: space-between;">
          <span>Order #${data.orderId}</span>
          <span>Official Receipt</span>
        </div>
      `;

      // Repeating Footer Template
      const footerTemplate = `
        <div style="font-size: 10px; width: 100%; border-top: 1px solid #eee; padding-top: 5px; margin: 0 40px; display: flex; justify-content: space-between;">
          <span>Generated by NodePdfGenerator</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `;

      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate,
        footerTemplate,
        margin: { top: '60px', bottom: '60px', left: '0px', right: '0px' },
      });

      return Buffer.from(pdfBuffer);
    } catch (error) {
      this.logger.error(`PDF generation failed. Retries remaining: ${retries}`, error.stack);
      if (retries > 0) return this.executePdfGeneration(data, retries - 1);
      throw new InternalServerErrorException('Failed to generate PDF');
    } finally {
      await context.close(); // Cleanup
    }
  }

  private getHtmlTemplate(data: GenerateReceiptDto, qrUrl: string): string {
    const itemsHtml = (data.items || []).map(item => `
      <tr>
        <td>${item.description}</td>
        <td style="text-align: right;">${item.quantity}</td>
        <td style="text-align: right;">$${item.rate.toFixed(2)}</td>
        <td style="text-align: right;">$${(item.quantity * item.rate).toFixed(2)}</td>
      </tr>
    `).join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
          <style>
              body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #333; }
              .watermark {
                  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg);
                  font-size: 150px; color: rgba(255, 0, 0, 0.05); z-index: -1; font-weight: bold;
              }
              .header { display: flex; justify-content: space-between; border-bottom: 2px solid #1a73e8; padding-bottom: 20px; margin-bottom: 30px; }
              .logo { height: 50px; }
              .details { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
              table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
              th { background: #f8f9fa; padding: 12px; text-align: left; border-bottom: 2px solid #eee; }
              td { padding: 12px; border-bottom: 1px solid #eee; }
              .total-section { text-align: right; border-top: 2px solid #1a73e8; padding-top: 10px; font-size: 24px; font-weight: bold; color: #1a73e8; }
              .qr-section { margin-top: 50px; display: flex; align-items: center; gap: 20px; }
              .qr-img { width: 100px; }
              tr { page-break-inside: avoid; }
          </style>
      </head>
      <body>
          <div class="watermark">PAID</div>
          <div class="header">
              <img src="${data.logoUrl}" class="logo">
              <div style="text-align: right;">
                  <h1 style="margin: 0; color: #1a73e8;">RECEIPT</h1>
                  <p>Order ID: ${data.orderId}</p>
              </div>
          </div>
          <div class="details">
              <div><h3>Billed To:</h3><p><strong>${data.name}</strong></p></div>
              <div style="text-align: right;"><h3>Date:</h3><p>${new Date().toLocaleDateString()}</p></div>
          </div>
          <table>
              <thead>
                  <tr><th>Description</th><th style="text-align: right;">Qty</th><th style="text-align: right;">Rate</th><th style="text-align: right;">Total</th></tr>
              </thead>
              <tbody>
                  ${itemsHtml || `<tr><td colspan="4" style="text-align: center; color: #888;">Service/Standard Payment</td></tr>`}
              </tbody>
          </table>
          <div style="display: flex; justify-content: flex-end;">
              <div class="total-section">Total Paid: $${data.amount.toFixed(2)}</div>
          </div>
          <div class="qr-section">
              <img src="${qrUrl}" class="qr-img">
              <p style="font-size: 12px; color: #888;">Scan to verify this transaction.<br>Secure Receipt by Antigravity.</p>
          </div>
      </body>
      </html>
    `;
  }
}
